cinema-after/config/routes.rb
Cinema::Application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :movies do
    resources :reviews
  end
  root to: 'movies#index'
end

cinema-after/app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :description, :image, :name
  has_many :reviews
end

cinema-after/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :movie
  attr_accessible :content, :name, :rating
end

cinema-after/app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

cinema-after/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

cinema-after/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

cinema-after/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.create!(params[:review])
    redirect_to @review.movie, notice: "Review has been created."
  end
end

cinema-after/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

cinema-after/app/helpers/application_helper.rb
module ApplicationHelper
end

cinema-after/app/helpers/movies_helper.rb
module MoviesHelper
end

cinema-after/app/helpers/reviews_helper.rb
module ReviewsHelper
end

cinema-after/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cinematron</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <div id="user_nav">
        <% if current_user %>
          Signed in as <strong><%= current_user.name %></strong>!
          <%= link_to "Sign out", signout_path, id: "sign_out" %>
        <% else %>
          <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
        <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

cinema-after/app/views/movies/_movie.html.erb
<div class="movie">
  <%= image_tag movie.image %>
  <h2><%= movie.name %></h2>
  <p><%= movie.description %></p>
  <% if current_page? movie %>
    <p><%= link_to "Back to Movies", movies_path %></p>
  <% else %>
    <p><%= link_to "Read Reviews", movie %></p>
  <% end %>
  <div class="clear"></div>
</div>

cinema-after/app/views/movies/index.html.erb
<h1>Movies</h1>

<%= render @movies %>

cinema-after/app/views/movies/show.html.erb
<div id="movie">
  <%= render @movie %>
</div>

<div id="reviews">
  <h2><%= pluralize @movie.reviews.size, "Review" %></h2>

  <% @movie.reviews.each do |review| %>
    <div class="review">
      <div class="content"><%= review.content %></div>
      <em>
        &mdash;
        <%= review.name %> gave it
        <strong><%= pluralize review.rating, "star" %></strong>
      </em>
    </div>
  <% end %>

  <h3>Write a review</h3>
  <%= form_for [@movie, Review.new] do |f| %>
    <div class="field">
      <%= f.label :rating %>
      <%= f.select :rating, 1..5 %>
    </div>
    <div class="field">
      <%= f.label :name, "Your name" %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.text_area :content, rows: 5, cols: 40 %>
    </div>
    <div class="actions"><%= f.submit %></div>
  <% end %>
</div>